services:
  db:
    image: postgres:15
    container_name: republica_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: republica123
      POSTGRES_DB: republica_pasteis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
